import React, { useState } from 'react'
import Sidebar from '../components/documentation/Sidebar/Sidebar'
import SidebarRes from '../components/documentation/SidebarResponsive/SidebarRes'
import { Article, ArticleTitle, ArticleSubTitle, Section, Scroll, ScrollTitle, ScrollSubTitle, ArticleP, Page, ScrollContainer } from '../components/documentation/ArticleElements'
import styled from 'styled-components'

export const List = styled.ul`
    margin-top: 25px;
    padding-left: 5.6%;
    width: 100%;
`;
export const ListItem = styled.li`
    margin: 10px 0;
`;

export const Link = styled.a`
    color: #0077ff;
    cursor: pointer;
    text-decoration: none;

    &:hover {
        text-decoration: underline;
    }
`;

const DescriptionMetadata = () => {
    const [isOpen, setIsOpen] = useState(false)

    const toggle = () => {
        setIsOpen(!isOpen)
    };
    return (
        <div>
            <SidebarRes isOpen={isOpen} toggle={toggle} />
            <Sidebar toggle={toggle}/>
            <Page
            initial = {{opacity: 0}}
            animate = {{opacity: 1}}
            transition = {{duration: 1}}> 
            <Article>
                <ArticleTitle>How to Structure the Dataset Description Metadata File</ArticleTitle>
                <Section className='background'>
                <ArticleSubTitle>Background</ArticleSubTitle>
                <ArticleP>SODA helps you prepare the <Link>dataset description metadata file</Link> conveniently. While SODA automatically generates the file in the required structure, we explain here how it must be structured according to the SPARC rules in order to provide some insight about the structure of the file generated by SODA.</ArticleP>
                </Section>

                <Section className='how-to'>
                <ArticleSubTitle>How To</ArticleSubTitle>
                <List>
                    <ListItem>Format: The dataset description file is accepted in either xlsx, csv, or json format. SODA generates it in the xlsx format based on the template provided by the Curation Team.</ListItem>
                    <ListItem>Location in the dataset: The dataset_description file must be included in the high-level dataset folder.</ListItem>
                    <ListItem>Content: The "Metadata element" and "Value" columns are mandatory as well as the "Definition" and "Example" columns, which should remain unchanged. Some of the "Metadata element" are mandatory (highlighted in bold below) for all datasets and must be provided at least one "Value". If more than one "Value" is to be provided (for instance multiple "Contributors") for a "Metadata Item", each subsequent value column must be named "Value 2", "Value 3", "Value 4", and so forth.
                        <List>
                            <ListItem><strong>Name</strong>: Descriptive title for the dataset. This field should match exactly with your dataset name on Blackfynn.</ListItem>
                            <ListItem><strong>Description</strong>: Brief description of the study and the data set. Equivalent to the abstract of a scientific paper. This could match the subtitle provided on Blackfynn.</ListItem>
                            <ListItem><strong>Keywords</strong>: A set of 3-5 keywords other than already mentioned in the above elements that will aid in search of your dataset once published on the SPARC portal. Each keyword must be provided in a separate column.</ListItem>
                            <ListItem><strong>Contributors</strong>: Name of any contributors to the dataset. These individuals need not have been authors on any publications describing the data, but should be acknowledged for their role in producing and publishing the dataset. If more than one, add each contributor in a new column. For each contributor it is mandatory at least one affiliation, at least one role, and role as contact person.</ListItem>
                            <ListItem><strong>Contributor ORCID ID</strong>: This is the contributor's ORCID ID number. If you do not have one, you can sign up for one at <Link>https://orcid.org</Link>. It must be in the format "https://orcid.org/xxxx-xxxx-xxxx-xxxx". It is not mandatory but highly recommended.</ListItem>
                            <ListItem><strong>Contributor Affiliation</strong>: Institutional affiliation for contributors. A <Link>ror ID</Link> in the "https://ror.org/xxxxxxxxx" format could be provided if available. If multiple affiliations, each must be semi-colon separated in a single cell.</ListItem>
                            <ListItem><strong>Contributor Role</strong>: Role(s) of the contributor. It must one of the following roles provided by the Data Cite schema: PrincipleInvestigator, Creator, CoInvestigator, ContactPerson, DataCollector, DataCurator, DataManager, Distributor, Editor, Producer, ProjectLeader, ProjectManager, ProjectMember, RelatedPerson, Researcher, ResearchGroup, Sponsor, Supervisor, WorkPackageLeader, Other. The definition of each of these roles is provided in the <Link>document here</Link>. The role "ContactPerson" must be provided for the person marked as "Yes" in the "Is Contact Person" element of the "Metadata Item" (this is done automatically in SODA). If more than one role is to be specified for a contributor, each must be comma-separated in a single cell.</ListItem>
                            <ListItem><strong>Is Contact Person</strong>: Specify "Yes" if the contributor is a contact person for the dataset, otherwise specify "No". One and only one of the contributors must be marked "Yes".</ListItem>
                            <ListItem>Acknowledgements: Acknowledgements beyond funding and contributors.</ListItem>
                            <ListItem><strong>Funding</strong>: Specify the number of your SPARC award (mandatory in the OT2OD0XXXXX format) and other funding award if applicable (optional). If multiple award numbers are specified, each award number must be specified in a separate column.</ListItem>
                            <ListItem>Originating Article DOI: DOIs of published articles that were generated from this dataset.</ListItem>
                            <ListItem><strong>Protocol URL or DOI</strong>: URLs (if still private) / DOIs (if public) of protocols from protocols.io related to this dataset.</ListItem>
                            <ListItem>Additional Links: URLs of additional resources used by this dataset (e.g., a link to a code repository).</ListItem>
                            <ListItem>Link Description: Short description of URL content.</ListItem>
                            <ListItem><strong>Number of subjects</strong>: Number of unique subjects in this dataset, should match subjects metadata file.</ListItem>
                            <ListItem><strong>Number of samples</strong>: Number of unique samples in this dataset, should match samples metadata file. Set to zero if there are no samples.</ListItem>
                            <ListItem>Completeness of data set: Is the data set as uploaded complete or is it part of an ongoing study? Use "hasNext" to indicate that you expect more data on different subjects as a continuation of this study. Use “hasChildren” to indicate that you expect more data on the same subjects or samples derived from those subjects. Leave empty if none of these two apply.</ListItem>
                            <ListItem>Parent dataset ID: If this is a part of a larger data set, or references subjects or samples from a parent dataset, provide the Blackfynn ID of the prior batch in the "N:dataset:c5c2f40f-76be-4979-bfc4-b9f9947231cf " format. You need only give us the Blackfynn ID of the last batch, not all batches. If samples and subjects are from multiple parent datasets please create a comma separated list of all parent Blackfynn IDs.</ListItem>
                            <ListItem>Title for complete data set: Please give us a provisional title for the entire data set.</ListItem>
                            <ListItem>Metadata Version DO NOT CHANGE: The "Value" for this must not be changed.</ListItem>
                        </List>
                        <ArticleP>Note: There should be only one of "Originating Article DOI", "Protocol URL or DOI", or "Additional Links" specified in each column. If there are multiple of those elements, each must be in a separate column. This is to avoid confusion about what the "Link Description" is for in case it is provided.</ArticleP>
                    </ListItem>
                    </List>
                </Section>
            </Article>
            <ScrollContainer>
            <Scroll>
                <ScrollTitle>In this article</ScrollTitle>
                <ScrollSubTitle to='background' smooth='true'>Background</ScrollSubTitle>
                <ScrollSubTitle to='how-to' smooth='true'>How To</ScrollSubTitle>
            </Scroll>
            </ScrollContainer>
            </Page>
        </div>
    )
}

export default DescriptionMetadata
