import React, { useState } from 'react'
import Sidebar from '../components/documentation/Sidebar/Sidebar'
import SidebarRes from '../components/documentation/SidebarResponsive/SidebarRes'
import { Article, ArticleTitle, ArticleSubTitle, Section, Scroll, ScrollTitle, ScrollSubTitle, ArticleP, Page, ScrollContainer } from '../components/documentation/ArticleElements'
import styled from 'styled-components'
import image1 from '../images/manifest-example.png'

export const Image = styled.img`
    width: 100%;
    
`;

export const ImgWrap =  styled.div`
    max-width: 700px;
    margin-top: 25px;
`;

export const List = styled.ul`
    margin-top: 25px;
    padding-left: 5.6%;
    width: 100%;
`;
export const ListItem = styled.li`
    margin: 10px 0;
`;

export const Link = styled.a`
    color: #0077ff;
    cursor: pointer;
    text-decoration: none;

    &:hover {
        text-decoration: underline;
    }
`;

const ManifestMetadata = () => {
    const [isOpen, setIsOpen] = useState(false)

    const toggle = () => {
        setIsOpen(!isOpen)
    };
    return (
        <div>
            <SidebarRes isOpen={isOpen} toggle={toggle} />
            <Sidebar toggle={toggle}/>
            <Page
            initial = {{opacity: 0}}
            animate = {{opacity: 1}}
            transition = {{duration: 1}}> 
            <Article>
                <ArticleTitle>How to Structure the Manifest Metadata File</ArticleTitle>
                <Section className='background'>
                <ArticleSubTitle>Background</ArticleSubTitle>
                <ArticleP>SODA helps you generate the <Link>manifest metadata files</Link> automatically. We explain here how it must be structured according to the SPARC rules in order to provide some insight about the structure of the file generated by SODA.</ArticleP>
                </Section>

                <Section className='how-to'>
                <ArticleSubTitle>How To</ArticleSubTitle>
                <List>
                    <ListItem>Format: the manifest file is accepted in either xlsx, csv, or json format. SODA generates it in the xlsx format based on the template provided by the Curation Team. A screenshot of the file is provided below.</ListItem>
                    <ImgWrap><Image src={image1} /></ImgWrap>
                    <ListItem>Location in the dataset: a manifest file is required in either 1) each of the high-level SPARC folders or 2) in each of the dataset folders with at least one file. SODA follows the structure #1 when generating the manifest files automatically for you.</ListItem>
                    <ListItem>Content: The "filename" and "timestamp" fields are mandatory and it is suggested to provide other fields as needed to understand each file.
                        <List>
                            <ListItem>Filename, structure #1: In structure #1, this should be path to the files relative to the high-level SPARC folder where the manifest file is located. For e.g, it would be "sub-1\ses-1\anat\anat-1-1.txt" for a manifest file located in the primary folder. Note that the extension of the file is included.</ListItem>
                            <ListItem>Filename, structure #2: In structure #2, this should be the name of the files located in the folder where the manifest file is located. For e.g., it would be "anat-1-1.txt" for a manifest file located under "sub-1\ses-1\anat" in the primary folder. Note that the extension of the file is included.</ListItem>
                            <ListItem>Timestamp: The last time the file was modified preferably in ISO format with UTC offset. For example, this would be "2019-07-13T02:43:14+05:30" for a file last modified on July 13th 2019 at 2:43 AM (14 seconds) in PST (thus +5:30 to show the offset from UTC).</ListItem>
                            <ListItem>File type: Type of this file. Would be '.txt' or 'Text file' for the file anat-1-1.txt.</ListItem>
                       </List>
                    </ListItem>
                    </List>
                </Section>
            </Article>
            <ScrollContainer>
            <Scroll>
                <ScrollTitle>In this article</ScrollTitle>
                <ScrollSubTitle to='background' smooth='true'>Background</ScrollSubTitle>
                <ScrollSubTitle to='how-to' smooth='true'>How To</ScrollSubTitle>
            </Scroll>
            </ScrollContainer>
            </Page>
        </div>
    )
}

export default ManifestMetadata
