import React, { useState } from 'react'
import Sidebar from '../components/documentation/Sidebar/Sidebar'
import SidebarRes from '../components/documentation/SidebarResponsive/SidebarRes'
import { Article, ArticleTitle, ArticleSubTitle, Section, Scroll, ScrollTitle, ScrollSubTitle, ArticleP, Page, ScrollContainer } from '../components/documentation/ArticleElements'
import styled from 'styled-components'
import image2 from '../images/data-deliverables-doc-example.png'
import image1 from '../images/submission-template.png'

export const Image = styled.img`
    width: 100%;
    
`;

export const ImgWrap =  styled.div`
    max-width: 700px;
    margin-top: 25px;
`;

export const List = styled.ul`
    margin-top: 25px;
    padding-left: 5.6%;
    width: 100%;
`;
export const ListItem = styled.li`
    margin: 10px 0;
`;

export const Link = styled.a`
    color: #0077ff;
    cursor: pointer;
    text-decoration: none;

    &:hover {
        text-decoration: underline;
    }
`;

const SubmissionMetadata = () => {
    const [isOpen, setIsOpen] = useState(false)

    const toggle = () => {
        setIsOpen(!isOpen)
    };
    return (
        <div>
            <SidebarRes isOpen={isOpen} toggle={toggle} />
            <Sidebar toggle={toggle}/>
            <Page
            initial = {{opacity: 0}}
            animate = {{opacity: 1}}
            transition = {{duration: 1}}> 
            <Article>
                <ArticleTitle>How to Structure the Submission Metadata File</ArticleTitle>
                <Section className='background'>
                <ArticleSubTitle>Background</ArticleSubTitle>
                <ArticleP>SODA helps you prepare the <Link>submission metadata file</Link> conveniently. We explain here how it must be structured according to the SPARC rules in order to provide some insight about the structure of the file generated by SODA.</ArticleP>
                </Section>

                <Section className='how-to'>
                <ArticleSubTitle>How To</ArticleSubTitle>
                <List>
                    <ListItem>Format: the submission file is accepted in either xlsx, csv, or json format. SODA generates it in the xlsx format based on the template provided by the Curation Team. A screenshot is provided below.</ListItem>
                    <ImgWrap><Image src={image1} style={{ marginBottom: 30 + 'px'}}></Image></ImgWrap>
                    <ListItem>Location in the dataset: The submission file must be included in the high-level dataset folder.</ListItem>
                    <ListItem>Content: The "Submission Item" and "Value" columns are mandatory (the "Definition" column could be kept or removed). Each of the three "Submission Item" element must be provided a "Value".
                        <List>
                            <ListItem>SPARC Award number: The number of your SPARC award.</ListItem>
                            <ListItem>Milestone achieved: This milestone must match <strong>exactly</strong> with one of the milestones agreed with the NIH in the Dataset Deliverables document. A screenshot of a sample Dataset Deliverables document is provided below. In case the dataset isn't related to a pre-agreed dataset, it should be explicitly mentioned (e.g., "Not included in the Dataset Deliverables document").</ListItem>
                            <ListItem>Milestone completion date: This date must match <strong>exactly</strong> with the completion date agreed with the NIH in the Dataset Deliverables document for the above mentioned "Milestone achieved". In the case the dataset isn't related to a pre-agreed milestone, it should be explicitly mentioned (e.g., "Not included in the Dataset Deliverables document").</ListItem>
                        </List>
                    </ListItem>
                    </List>
                    <ImgWrap><Image src={image2} style={{maxWidth: 400  + 'px'}}></Image></ImgWrap>
                    <p style={{fontStyle:  'italic', textAlign: 'center'}}>A screenshot of our a demo Data Deliverables document. The "Milestone achieved" value in the submission file must be one of the milestone specified under "Related milestone, aim, or task" of the document and the "Milestone completion date" must be the corresponding "Expected date of completion" in the document.</p>
                </Section>
            </Article>
            <ScrollContainer>
            <Scroll>
                <ScrollTitle>In this article</ScrollTitle>
                <ScrollSubTitle to='background' smooth='true'>Background</ScrollSubTitle>
                <ScrollSubTitle to='how-to' smooth='true'>How To</ScrollSubTitle>
            </Scroll>
            </ScrollContainer>
            </Page>
        </div>
    )
}

export default SubmissionMetadata
