import { useState } from "react";
import { Table, Checkbox, Text } from "@mantine/core";
import FullWidthContainer from "../../containers/FullWidthContainer";

const DatasetContentSelector = () => {
  const [selectedComponents, setSelectedComponents] = useState([]);

  const options = [
    {
      value: "subjects",
      label: "Subjects",
      description:
        "Individual entities, such as humans, animals, or other organisms, that participated in the study.",
    },
    {
      value: "samples",
      label: "Samples",
      description:
        "Biological or chemical specimens collected from subjects for further analysis or experimentation.",
      dependsOn: "subjects",
    },
    {
      value: "sites",
      label: "Sites",
      description:
        "Specific locations in the body, environment, or experimental setup where data or samples were collected.",
      dependsOn: "subjects",
    },
    {
      value: "performances",
      label: "Performances",
      description: "Repeated experimental runs or iterations conducted as part of the study.",
      dependsOn: "subjects",
    },
    {
      value: "code",
      label: "Code",
      description:
        "Scripts, computational models, or analysis pipelines used in or generated by the study.",
    },
  ];
  const toggleSelection = (value) => {
    setSelectedComponents((prev) =>
      prev.includes(value) ? prev.filter((item) => item !== value) : [...prev, value]
    );
  };

  return (
    <FullWidthContainer>
      <Text size="lg" weight={500} mb="md">
        Select all of the following that apply to the data you collected:
      </Text>

      <Table withTableBorder>
        <Table.Thead>
          <Table.Tr>
            <Table.Th></Table.Th>
            <Table.Th>My dataset contains</Table.Th>
            <Table.Th>Description</Table.Th>
          </Table.Tr>
        </Table.Thead>
        <Table.Tbody>
          {options.map((option) => {
            const isDisabled = option.dependsOn && !selectedComponents.includes(option.dependsOn);

            return (
              <Table.Tr key={option.value}>
                <Table.Td>
                  <Checkbox
                    checked={selectedComponents.includes(option.value)}
                    onChange={() => toggleSelection(option.value)}
                    disabled={isDisabled}
                  />
                </Table.Td>
                <Table.Td>{option.label}</Table.Td>
                <Table.Td>{option.description}</Table.Td>
              </Table.Tr>
            );
          })}
        </Table.Tbody>
      </Table>
    </FullWidthContainer>
  );
};

export default DatasetContentSelector;
