name: SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with: 
          args: >
            -Dsonar.projectKey=fairdataihub_SODA-for-SPARC
            -Dsonar.organization=fairdataihub
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}